#!/usr/bin/env python

import argparse
import os
import logging

__author__ = "Kyle Bystrom"
__maintainer__ = "Kyle Bystrom"
__email__ = "kylebystrom@berkeley.edu"

parser = argparse.ArgumentParser(description="General analysis and compilation script for pawpyseed")

subparsers = parser.add_subparsers()
parser_compile = subparsers.add_parser("compile", help="Compile the C code for pawpyseed")
parser_cdt = subparsers.add_parser("cdt", help="Run defect band composition analysis on a"
									"pycdt-generated defect directory system")
parser_analyze = subparsers.add_parser("analyze", help="Perform analysis on pawpyseed-generated data")
